name: flutter_calculator
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  decimal: ^2.3.3
  flutter:
    sdk: flutter
  provider: ^6.1.1

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  test: ^1.24.9
  very_good_analysis: ^5.1.0
flutter:
  uses-material-design: true
